name: Documentation

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade -r ci_requirements_doc.txt
    - name: Install module
      run: |
        python3 -m pip install . 
    - name: Building documentation
      run: |
        cd doc
        make html
    - name: Deploying documentation
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./doc/build/html # The folder the action should deploy.
